### ISSUE TITLE
Is this a good option to use in production?

### ISSUE THREAD

**Issue by EnderDev** [novifinancial/opaque-ke#154]
Hiya,

I found out about OPAQUE from Cloudflare's blog and stumbled upon this Rust implementation of it. I just wanted to know whether this would be a good choice to use in production. 

I'd appreciate your thoughts.

**Comment by kevinlewi** [comment]
Hi @EnderDev, this implementation was produced with production-readiness definitely in mind, and we would be happy to help with answering any questions on how to use this library, future features, etc.

Having said that, there is one caveat to take into account: Since the official OPAQUE RFC draft has not fully settled (https://github.com/cfrg/draft-irtf-cfrg-opaque), this implementation is subject to change in future versions. At the moment, the latest release (v0.5.0) is in compliance with v03 of the draft (https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-03.html), but there is a high likelihood that the final, standardized version of OPAQUE will not be compatible with v0.5.0.

We do intend to keep parity with future versions of the draft as they are published. But it would be good to keep in mind that if you use v0.5.0, and the OPAQUE protocol changes in the future, you would potentially have to upgrade to a later version if you wanted those changes.

Hope this gives you a sense of where things are with this library and whether or not it is ready for production. Actually, if there are any major blockers for using this in production other than the one mentioned above, we are very much open to feedback on that! Feel free to open more issues with questions if they come up. Thanks!

**Comment by EnderDev** [comment]
Awesome, thank you! I will definitely be using this in production 👍
