### ISSUE TITLE
Using a separate key pair for fake response

### ISSUE THREAD

**Issue by daxpedda** [novifinancial/opaque-ke#183]
I was wondering why there is a separate key pair created specifically for fake responses. If the server is re-using the same key pairs for all/many accounts, which is now hinted at with `ServerSetup`, it might be easy for the client to distinguish between fake and authentic responses by the public key used.

**Comment by kevinlewi** [comment]
Hi, good question. This keypair is used to fake the client's public key that would normally be present in their password file after the registration phase. In the generation of a faked credential response, the server needs to pull a public key from somewhere. At the moment, the spec has this parameter generated at setup/initialization time, because the alternative of generating one on each invocation of ServerLogin::start() introduces a potentially exploitable timing attack (since the faked responses will do one more group exponentiation than the authentic responses).

>  it might be easy for the client to distinguish between fake and authentic responses by the public key used.

The catch is that the public key is not actually sent over in the CredentialResponse message in cleartext -- it is masked by a masking_key, which can only be obtained if the client has the right password.

This implementation is as described on this issue: https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/219

And for more context, here are past discussions on how we arrived at the current design for user enumeration mitigation:
- https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/210
- https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/215
- https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/22

I will close this issue here, but feel free to either reopen with more questions, or you can also post an issue directly to the draft-irtf-cfrg-opaque repo if you have questions around the design itself (outside of this implementation)!

**Comment by bytemare** [comment]
Hi 👋
