### ISSUE TITLE
Remote private key

### ISSUE THREAD

**Issue by daxpedda** [novifinancial/opaque-ke#199]
Currently there is no support for remote private keys in opaque-ke. Meaning that the use of HSMs or "vault storage"s to store the private key in `ServerSetup` isn't currently possible.

I am working towards an implementation and am planning to provide a PR to support this. Is my assumption correct that the only work the private key does is a DH key exchange, basically the remote key has to provide a replacement of this function?:
https://github.com/novifinancial/opaque-ke/blob/349329cdebf35bbb3767413ea8905aa4ababbf02/src/keypair.rs#L109-L118
I understand if opaque-ke doesn't want to implement support for this, but at least some API changes have to be made to allow external implementations to provide support.

**Comment by kevinlewi** [comment]
Can you clarify what you mean by "remote private key" here? Do you mean that the HSM already has a designated private key, which you would like to use in OPAQUE instead of the one that that is generated from a `ServerSetup`?

If so, would it perhaps be simpler to just use that private key to encrypt the `ServerSetup` object, so that only the HSM can decrypt it, and then proceed with OPAQUE without having to worry about injecting this external HSM private key into the AKE for OPAQUE?

Hope that makes sense...

**Comment by daxpedda** [comment]
> Can you clarify what you mean by "remote private key" here? Do you mean that the HSM already has a designated private key, which you would like to use in OPAQUE instead of the one that that is generated from a `ServerSetup`?

Really the idea is to never commit the private key to memory, therefore opaque-ke never get's access to the private key. Which then requires all necessary cryptographic functions to be executed by the device holding the private key, HSMs are built exactly for that purpose.

> If so, would it perhaps be simpler to just use that private key to encrypt the `ServerSetup` object, so that only the HSM can decrypt it, and then proceed with OPAQUE without having to worry about injecting this external HSM private key into the AKE for OPAQUE?

If the goal would be to never leak the private key of the server setup to the server, this isn't an option. This also allows to use the same keypair that is used for other purposes, like for example the HTTPS certificate.

**Comment by kevinlewi** [comment]
I am not quite sure we are considering the same proposal (perhaps there is still a misunderstanding), let me try to be more concrete with what I mean. And sorry if this is too pedantic :)

So, typically an HSM has some private keypair (SK, PK), with the guarantee that SK never leaves the HSM. It seems that you want to execute OPAQUE within the HSM. When running ServerSetup, another keypair gets generated that is used only in OPAQUE: let's call it (OSK, OPK).

During the key exchange portion of OPAQUE, however, you would like (SK, PK) to be used, instead of (OSK, OPK).

My question is: why not use SK to produce a ciphertext C representing a serialized version of the `ServerSetup` object:
`C = Encrypt(SK, (OSK, OPK))`, and persist C outside of the HSM enclave across client registrations.

Then, when running the key exchange portion, the HSM code could decrypt C to recover the `ServerSetup` object, and then run the opaque-ke code using this object.

So, the key exchange would not actually be using the original (SK, PK) corresponding to the HSM, but it also does not leak SK to anything outside of the HSM enclave.

Would this suffice for your use-case?

**Comment by daxpedda** [comment]
- Most HSMs don't support encrypting with the SK and if they do, only with RSA usually
- Additionally, what would be a nice-to-have, is to never leak the `ServerSetup` at all, it would then have the same security properties as SK, with your proposal, `ServerSetup` would be leaked to memory, even if temporarily
- On top of that, the original use-case would be to use the same SK and PK for `ServerSetup`, as is used for HTTPS's PKI for example, that way, the client can always verify OPAQUE during registration, I know this isn't OPAQUE-TLS, but it's still a very nice-to-have

**Comment by kevinlewi** [comment]
Follow-up: #214
