### ISSUE TITLE
Version 0.6.1 (draft-irtf-cfrg-opaque-05) support for p256/SHA256

### ISSUE THREAD

**Issue by jaroslavsaxa** [novifinancial/opaque-ke#267]
Hi All

Is it possible to make somehow version 0.6.1 implementing draft-irtf-cfrg-opaque-05 running for p256/SHA256 something like 
main [draft-irtf-cfrg-opaque-07]
  type OprfGroup = p256_::ProjectivePoint;
    type KeGroup = p256_::PublicKey;
    type KeyExchange = opaque_ke::key_exchange::tripledh::TripleDH;
    type Hash = sha2::Sha256;
    type SlowHash = opaque_ke::slow_hash::NoOpHash;
or version 0.6.1 is only for Group = curve25519_dalek::ristretto::RistrettoPoint/Hash = sha2::Sha512

**Comment by daxpedda** [comment]
The next release will support P-256. Currently blocked on #261.

**Comment by daxpedda** [comment]
I noticed I didn't properly read your question because of offline-discussions. I don't think back-porting the P-256 implementation to version 0.6.1 is viable by any means.

Our old implementation during 1.0 and up used some pretty horrible code written by me (not a cryptographer) that was marked experimental.

The new P-256 implementation piggybacks on a [great implementation in RustCrypto's `elliptic-curve`](https://docs.rs/elliptic-curve/0.12.0-pre.1/elliptic_curve/hash2curve/index.html), which isn't compatible with the MSRV of 0.6.
