### ISSUE TITLE
Convert `CredentialRequest` between 0.6 and 2.0

### ISSUE THREAD

**Issue by nitnelave** [novifinancial/opaque-ke#285]
I'm in the process of migrating from 0.6 to 2.0, but I'm running into the following problem: I have a DB that stores `CredentialRequest` as "password" (i.e. information needed to check the password), but these do not deserialize properly anymore with the new version.
Has the data format changed? Is it possible to convert from one to the other, or is the data incompatible?

**Comment by kevinlewi** [comment]
The data formats between 0.6 and 2.0 are indeed incompatible.

**Comment by kevinlewi** [comment]
In general, any records between different major versions of the library will be incompatible with one another, since they implement different versions of the OPAQUE ietf draft.

For instance, 2.0 is tied to [draft-irtf-cfrg-opaque-10](https://datatracker.ietf.org/doc/draft-irtf-cfrg-opaque/10/), whereas 0.6 is tied to [draft-irtf-cfrg-opaque-05](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-05.html).

Closing this issue, but feel free to re-open if you have more questions!
