### ISSUE TITLE
Prevent user enumeration

### ISSUE THREAD

**Issue by louisabraham** [novifinancial/opaque-ke#38]
There are countermeasures described in the draft https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#name-user-enumeration

The first doesn't require any change to the client and simply fakes the protocol for an inexistent user.
The second is more complex (involves the OPRR) but prevents learning (User registered OR User changed password) when reusing the same alpha.

Do you plan to implement at least the first? I can help!

**Comment by kevinlewi** [comment]
The first countermeasure isn't a part of the OPAQUE protocol itself (if I am understanding correctly), and hence should be left to the caller of the OPAQUE API rather than being integrated into this library.

The second countermeasure is certainly interesting, although I am not sure how important it is to provide protection against an attacker trying to learn if a user has changed their password or not. I think we should probably aim towards matching the main parts of the RFC draft before addressing this one.

In any case, thank you very much for offering to help!
